// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvjgdwwvrpplqieoshtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12amdkd3d2cnBwbHFpZW9zaHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzU3NTcsImV4cCI6MjA3MzI1MTc1N30.DQep1B4jllQQMZslyY9sntrW-WXi2sInkmUDQl8-U-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});